INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_VHFPULSESENDER2 VHFPulseSender2)

FIND_PATH(
    VHFPULSESENDER2_INCLUDE_DIRS
    NAMES VHFPulseSender2/api.h
    HINTS $ENV{VHFPULSESENDER2_DIR}/include
        ${PC_VHFPULSESENDER2_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    VHFPULSESENDER2_LIBRARIES
    NAMES gnuradio-VHFPulseSender2
    HINTS $ENV{VHFPULSESENDER2_DIR}/lib
        ${PC_VHFPULSESENDER2_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/VHFPulseSender2Target.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VHFPULSESENDER2 DEFAULT_MSG VHFPULSESENDER2_LIBRARIES VHFPULSESENDER2_INCLUDE_DIRS)
MARK_AS_ADVANCED(VHFPULSESENDER2_LIBRARIES VHFPULSESENDER2_INCLUDE_DIRS)
