INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_VHFPULSEDETECT2 VHFPulseDetect2)

FIND_PATH(
    VHFPULSEDETECT2_INCLUDE_DIRS
    NAMES VHFPulseDetect2/api.h
    HINTS $ENV{VHFPULSEDETECT2_DIR}/include
        ${PC_VHFPULSEDETECT2_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    VHFPULSEDETECT2_LIBRARIES
    NAMES gnuradio-VHFPulseDetect2
    HINTS $ENV{VHFPULSEDETECT2_DIR}/lib
        ${PC_VHFPULSEDETECT2_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/VHFPulseDetect2Target.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VHFPULSEDETECT2 DEFAULT_MSG VHFPULSEDETECT2_LIBRARIES VHFPULSEDETECT2_INCLUDE_DIRS)
MARK_AS_ADVANCED(VHFPULSEDETECT2_LIBRARIES VHFPULSEDETECT2_INCLUDE_DIRS)
